# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  # Custom environment variables to be set during the builds.
  - env:
      - CGO_ENABLED=0
    # For more info refer to: https://golang.org/doc/install/source#environment
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    main: ./cmd/gomls/
archives:
  # Optionally override the matrix generation and specify only the final list of targets.
  - format: binary
    name_template: "{{ tolower .ProjectName }}_{{ .Os }}"
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  footer: |

    ---

    _Released with [GoReleaser](https://goreleaser.com)!_